### ISSUE TITLE
Strict is_a() function is Deprecated.

### ISSUE THREAD

**Issue by Sunnygolden8** [EmpathyApp/EmpathyApp#62]
![untitled](https://cloud.githubusercontent.com/assets/5623612/5910075/bc6c42f4-a573-11e4-87d8-c9cb188e26d0.png)

**Comment by SunyataZero** [comment]
Yes, this is a warning that we have because we are running php version 5.2,
here's some info i found:
"The is_a() function is a PHP4 function that was deprecated in PHP version
5.0.0, but then brought back in 5.3.0."
(from
https://wordpress.org/support/topic/error-message-is_a-deprecated-please-use-the-instanceof-operator
)
It's good that you found this warning though, maybe there is a workaround,
not sure. Otherwise we could move it into this file:
https://github.com/EmpathyApp/EmpathyApp/blob/master/docs/dependencies/risks-and-defects.md
Kind Regards,
Tord

On Mon, Jan 26, 2015 at 11:55 PM, Christine Lam <notifications@github.com>
wrote:

> [image: untitled]
> <https://cloud.githubusercontent.com/assets/5623612/5910075/bc6c42f4-a573-11e4-87d8-c9cb188e26d0.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/EmpathyApp/EmpathyApp/issues/62>.
>



-- 
https://github.com/EmpathyApp/EmpathyApp/
<http://www.svenskafreds.se/fredskalender-for-goteborg>
http://ihavearrived.org/

**Comment by Sunnygolden8** [comment]
Okay, cool. I'll just close this issue then.
