### ISSUE TITLE
Completing and approving the requirements specification

### ISSUE THREAD

**Issue by SunyataZero** [EmpathyApp/EmpathyApp#66]
Version 0.1.2 available here:
https://github.com/EmpathyApp/EmpathyApp/blob/master/docs/design/requirements-spec.md
(It's possible to edit by clicking on the pen icon in the upper right of the document window)

**Comment by SunyataZero** [comment]
I've now gone through the entire document again
https://github.com/EmpathyApp/EmpathyApp/blob/master/docs/design/requirements-spec.md
and made some updates (but there are still areas that are not done or completed)

**Comment by Peijman** [comment]
the link above doesnt work

**Comment by SunyataZero** [comment]
@Peijman Ok, there's been an update of the path, here's the new one:
https://github.com/EmpathyApp/EmpathyApp/blob/master/docs/planning/requirements-spec.md

**Comment by Peijman** [comment]
I love that you put this together! Some general thoughts I am having about this are that we should make this document easier for people to access, and a little simpler so that people can catch up on things really fast. I think it's pretty good, just needs some editing. What I'm thinking is that all documentation should be as streamlined and simple and clear as possible so that devs can understand what is going on and what they can do really quickly. Absolutely great job so far! I'll try to edit this within the next week.

**Comment by SunyataZero** [comment]
Thank you, this document is meant to be on the formal side, but i agree that it's important to make it easy for the devs to have a low so-called "hacktivation energy" :) (the amount of work to be done before starting to play with the source code and seeing changes)

One reason for having such an extensive document is that we have less of a risk of missing something, and if some area is too detailed we can just put "todo" or "tbd" or something else, and for planned features simply "planned"

Actually because you brought this up i realized a way to connect an important document to [the intro docs](https://github.com/EmpathyApp/EmpathyApp/tree/master/docs/intro) others, will fix this soon

**Comment by SunyataZero** [comment]
@Peijman Can we close this issue? Or what is the status right now?
