### ISSUE TITLE
neat skype still calls empathizer even if logged out!

### ISSUE THREAD

**Issue by Peijman** [EmpathyApp/EmpathyApp#81]

**Comment by Peijman** [comment]
It even calls me if I am signed out of skype!

**Comment by SunyataZero** [comment]
@Peijman: don't think there's a way around this other than simply removing the phone number from the empathizer accounts. Maybe this is ok since we are advicing empathizers to use a separate account for empathy app calls?
https://github.com/EmpathyApp/EmpathyApp/blob/master/docs/misc/empathizer-user-guide.md

**Comment by Peijman** [comment]
Ok I resolved this. You just have to make sure that your # is not listed in your skype app on your phone.

**Comment by SunyataZero** [comment]
But this resolution was for the new issue #82 right? we still have the problem in the title right?

**Comment by Peijman** [comment]
yes. This still happens. But it is not a problem necessarily, but ideally it should not do anything if the status says offline.

**Comment by SunyataZero** [comment]
Ok, i think (not sure) what happens is that if you are offline you are moved to the end of the "queue" of people to call

**Comment by Peijman** [comment]
yes, but it still calls you, but not a big deal.
